# This is the master template. It must come first.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# This section is for your local development machine.
development:
  <<: *default
  database: backend_development

# This section is for running automated tests.
test:
  <<: *default
  database: backend_test

# This is the section for Railway (production).
production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>