# Generated by Django 5.2.3 on 2025-06-25 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_favorite',
        ),
    ]
