# Generated by Django 5.2.3 on 2025-06-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_photo_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='alt',
        ),
    ]
