# Generated by Django 5.2.3 on 2025-06-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_title_photo_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='hex_color',
            new_name='avg_color',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='portfolio_url',
            new_name='photographer_url',
        ),
    ]
