# Generated by Django 4.2.12 on 2024-05-13 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.BigIntegerField(unique=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('url', models.URLField(max_length=1024)),
                ('avg_color', models.CharField(max_length=7)),
                ('original_url', models.URLField(max_length=1024)),
                ('large2x_url', models.URLField(max_length=1024)),
                ('large_url', models.URLField(max_length=1024)),
                ('medium_url', models.URLField(max_length=1024)),
                ('small_url', models.URLField(max_length=1024)),
                ('portrait_url', models.URLField(max_length=1024)),
                ('landscape_url', models.URLField(max_length=1024)),
                ('tiny_url', models.URLField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portfolio', models.URLField(max_length=1024)),
                ('photographer_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='photos.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'photo')},
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='owner',
            field=models.ManyToManyField(related_name='photos', through='photos.UserPhoto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.photographer'),
        ),
    ]
