# Generated by Django 5.0.5 on 2024-05-07 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer', models.CharField(max_length=254)),
                ('photographer_url', models.URLField(blank=True, max_length=2083, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='photos')),
                ('image_url', models.URLField(blank=True, max_length=2083, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('likes', models.ManyToManyField(through='photos.Like', to=settings.AUTH_USER_MODEL, verbose_name='likes')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('photo', 'user')},
        ),
    ]
