# Generated by Django 5.0.7 on 2025-07-08 01:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(help_text='Photo that was liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='photos.photo')),
                ('user', models.ForeignKey(help_text='User who liked the photo', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'db_table': 'likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='likes_user_id_4c8dad_idx'), models.Index(fields=['photo'], name='likes_photo_i_fd21d4_idx'), models.Index(fields=['created_at'], name='likes_created_6ac82b_idx'), models.Index(fields=['-created_at'], name='likes_created_22ad1e_idx'), models.Index(fields=['user', 'photo'], name='likes_user_id_19c91c_idx')],
                'unique_together': {('user', 'photo')},
            },
        ),
    ]
