# Generated by Django 5.0.7 on 2025-07-08 01:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pexels_id', models.IntegerField(help_text='Unique ID from Pexels API', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('url', models.URLField(help_text='Pexels photo page URL', max_length=500)),
                ('photographer', models.CharField(max_length=255)),
                ('photographer_url', models.URLField(blank=True, max_length=500)),
                ('photographer_id', models.IntegerField(blank=True, null=True)),
                ('avg_color', models.CharField(blank=True, help_text='Average color in hex format (e.g., #FF5733)', max_length=7)),
                ('src_original', models.URLField(max_length=500)),
                ('src_large', models.URLField(blank=True, max_length=500)),
                ('src_medium', models.URLField(blank=True, max_length=500)),
                ('src_small', models.URLField(blank=True, max_length=500)),
                ('alt_text', models.TextField(blank=True, help_text='Alternative text for accessibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'photos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pexels_id'], name='photos_pexels__46caee_idx'), models.Index(fields=['photographer'], name='photos_photogr_cb8bb7_idx'), models.Index(fields=['created_at'], name='photos_created_cc8839_idx'), models.Index(fields=['photographer_id'], name='photos_photogr_7dcdc1_idx'), models.Index(fields=['-created_at'], name='photos_created_eacd5b_idx')],
            },
        ),
    ]
