# Generated by Django 4.2.22 on 2025-06-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
