# Generated by Django 4.2.23 on 2025-07-11 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('url', models.URLField()),
                ('photographer', models.CharField(max_length=255)),
                ('photographer_url', models.URLField()),
                ('photographer_id', models.IntegerField()),
                ('avg_color', models.CharField(max_length=7)),
                ('src_original', models.URLField()),
                ('src_large2x', models.URLField()),
                ('src_large', models.URLField()),
                ('src_medium', models.URLField()),
                ('src_small', models.URLField()),
                ('src_portrait', models.URLField()),
                ('src_landscape', models.URLField()),
                ('src_tiny', models.URLField()),
                ('alt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'photo')},
            },
        ),
    ]
