# Generated by Django 5.2.4 on 2025-07-07 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photographer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True, null=True)),
                ("pexels_id", models.PositiveBigIntegerField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Photographer",
                "verbose_name_plural": "Photographers",
                "db_table": "photographers",
                "db_table_comment": "Table containing photographer information.",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("url", models.URLField()),
                ("alt", models.TextField(blank=True, null=True)),
                ("avg_color", models.CharField(blank=True, max_length=7, null=True)),
                ("src_original", models.URLField(blank=True, null=True)),
                ("src_large2x", models.URLField(blank=True, null=True)),
                ("src_large", models.URLField(blank=True, null=True)),
                ("src_medium", models.URLField(blank=True, null=True)),
                ("src_small", models.URLField(blank=True, null=True)),
                ("src_portrait", models.URLField(blank=True, null=True)),
                ("src_landscape", models.URLField(blank=True, null=True)),
                ("src_tiny", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="photo_gallery.photographer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "db_table": "photos",
                "db_table_comment": "Table containing photo information.",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="photo_gallery.photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes",
                "db_table": "likes",
                "db_table_comment": "Table containing likes on photos.",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "photo"], name="likes_user_id_19c91c_idx"
                    )
                ],
                "unique_together": {("user", "photo")},
            },
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["photographer", "url"], name="photos_photogr_4199f6_idx"
            ),
        ),
    ]
